# development:
#   adapter: async

# test:
#   adapter: async

# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: live_production
production: &production
  url: redis://localhost:6379
  adapter: redis
development: &development
  url: redis://localhost:6379
test: *developmen